wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    t:
      4: 3.9.10
      5: 0.10.21
      8:
      - 5
a:
  desc: null
  value: 4.0
b:
  desc: null
  value: 3.0
