main:
  project_name: ml_data_pipeline
  experiment_name: dev
  execute_steps:
    - download
    - preprocess
    - checkdata
    - segregate
  # This seed will be used to seed the random number generator
  # to ensure repeatibility of the data splits and other
  # pseudo-random operations
  random_seed: 112233
data:
  file_url: "https://github.com/wasuratme96/Machine-Learning-DevOps-Engineering/blob/main/Reproducible%20ML%20Pipeline/ML%20Data%20Pipeline%20HandsOn/data/genres_data_mod1.parquet?raw=true"
  reference_dataset: "ml_data_pipeline/preprocessed_data.csv:latest"
  # Threshold for Kolomorov-Smirnov test
  ks_alpha: 0.05
  test_size: 0.3
  val_size: 0.3
  # Stratify according to the target when splitting the data
  # in train/test or in train/val
  stratify: genre